#!/usr/bin/env python3
"""
Convert portable field element constants (int32_t[10], radix-2^25.5)
to fe51 format (uint64_t[5], radix-2^51) for x64 optimization.

Outputs constants in uint64_t[5] format for use with fe = uint64_t[5].
"""

import re
import os

def portable_to_value(limbs_10):
    """Reconstruct the 255-bit value from portable limbs (signed, alternating 26/25-bit)."""
    shifts = [0, 26, 51, 77, 102, 128, 153, 179, 204, 230]
    value = sum(int(limb) * (1 << shift) for limb, shift in zip(limbs_10, shifts))
    p = (1 << 255) - 19
    value = value % p
    return value

def value_to_fe51(value):
    """Pack a value into 5 x 51-bit limbs."""
    mask = (1 << 51) - 1
    limbs = []
    for i in range(5):
        limbs.append(value & mask)
        value >>= 51
    return limbs

def portable_to_fe51(limbs_10):
    """Convert portable limbs to fe51 limbs."""
    value = portable_to_value(limbs_10)
    return value_to_fe51(value)

def format_fe51(limbs):
    """Format fe51 limbs as C initializer with ULL suffix."""
    return "{" + ", ".join(f"0x{l:013x}ULL" for l in limbs) + "}"

def format_portable(limbs):
    """Format portable limbs as C initializer."""
    return "{" + ", ".join(str(l) for l in limbs) + "}"

# Standalone constants used in source files
constants = {
    "fe_d": [-10913610, 13857413, -15372611, 6949391, 114729, -8787816, -6275908, -3247719, -18696448, -12055116],
    "fe_sqrtm1": [-32595792, -7943725, 9377950, 3500415, 12389472, -272473, -25146209, -2005654, 326686, 11406482],
    "fe_d2": [-21827239, -5839606, -30745221, 13898782, 229458, 15978800, -12551817, -6495438, 29715968, 9444199],
    "fe_ma": [-486662, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "fe_ma2": [-12721188, -3529, 0, 0, 0, 0, 0, 0, 0, 0],
    "fe_fffb1": [-31702527, -2466483, -26106795, -12203692, -12169197, -321052, 14850977, -10296299, -16929438, -407568],
    "fe_fffb2": [8166131, -6741800, -17040804, 3154616, 21461005, 1466302, -30876704, -6368709, 10503587, -13363080],
    "fe_fffb3": [-13620103, 14639558, 4532995, 7679154, 16815101, -15883539, -22863840, -14813421, 13716513, -6477756],
    "fe_fffb4": [-21786234, -12173074, 21573800, 4524538, -4645904, 16204591, 8012863, -8444712, 3212926, 6885324],
}

print("// Fe51 precomputed constants for x64 platform (uint64_t[5] format)")
print("// Generated by scripts/generate_fe51_tables.py")
print()

for name, limbs in constants.items():
    fe51 = portable_to_fe51(limbs)
    value = portable_to_value(limbs)
    print(f"// {name}")
    print(f"//   portable: {format_portable(limbs)}")
    print(f"//   value: 0x{value:064x}")
    print(f"//   fe51:  {format_fe51(fe51)}")
    print()

# Generate the ge_Bi table
ge_Bi = [
    [[25967493, -14356035, 29566456, 3660896, -12694345, 4014787, 27544626, -11754271, -6079156, 2047605],
     [-12545711, 934262, -2722910, 3049990, -727428, 9406986, 12720692, 5043384, 19500929, -15469378],
     [-8738181, 4489570, 9688441, -14785194, 10184609, -12363380, 29287919, 11864899, -24514362, -4438546]],
    [[15636291, -9688557, 24204773, -7912398, 616977, -16685262, 27787600, -14772189, 28944400, -1550024],
     [16568933, 4717097, -11556148, -1102322, 15682896, -11807043, 16354577, -11775962, 7689662, 11199574],
     [30464156, -5976125, -11779434, -15670865, 23220365, 15915852, 7512774, 10017326, -17749093, -9920357]],
    [[10861363, 11473154, 27284546, 1981175, -30064349, 12577861, 32867885, 14515107, -15438304, 10819380],
     [4708026, 6336745, 20377586, 9066809, -11272109, 6594696, -25653668, 12483688, -12668491, 5581306],
     [19563160, 16186464, -29386857, 4097519, 10237984, -4348115, 28542350, 13850243, -23678021, -15815942]],
    [[5153746, 9909285, 1723747, -2777874, 30523605, 5516873, 19480852, 5230134, -23952439, -15175766],
     [-30269007, -3463509, 7665486, 10083793, 28475525, 1649722, 20654025, 16520125, 30598449, 7715701],
     [28881845, 14381568, 9657904, 3680757, -20181635, 7843316, -31400660, 1370708, 29794553, -1409300]],
    [[-22518993, -6692182, 14201702, -8745502, -23510406, 8844726, 18474211, -1361450, -13062696, 13821877],
     [-6455177, -7839871, 3374702, -4740862, -27098617, -10571707, 31655028, -7212327, 18853322, -14220951],
     [4566830, -12963868, -28974889, -12240689, -7602672, -2830569, -8514358, -10431137, 2207753, -3209784]],
    [[-25154831, -4185821, 29681144, 7868801, -6854661, -9423865, -12437364, -663000, -31111463, -16132436],
     [25576264, -2703214, 7349804, -11814844, 16472782, 9300885, 3844789, 15725684, 171356, 6466918],
     [23103977, 13316479, 9739013, -16149481, 817875, -15038942, 8965339, -14088058, -30714912, 16193877]],
    [[-33521811, 3180713, -2394130, 14003687, -16903474, -16270840, 17238398, 4729455, -18074513, 9256800],
     [-25182317, -4174131, 32336398, 5036987, -21236817, 11360617, 22616405, 9761698, -19827198, 630305],
     [-13720693, 2639453, -24237460, -7406481, 9494427, -5774029, -6554551, -15960994, -2449256, -14291300]],
    [[-3151181, -5046075, 9282714, 6866145, -31907062, -863023, -18940575, 15033784, 25105118, -7894876],
     [-24326370, 15950226, -31801215, -14592823, -11662737, -5090925, 1573892, -2625887, 2198790, -15804619],
     [-3099351, 10324967, -2241613, 7453183, -5446979, -2735503, -13812022, -16236442, -32461234, -12290683]],
]

print("// ge_Bi table in fe51 format (uint64_t[5])")
print("static const ge_precomp ge_Bi[8] = {")
for i, point in enumerate(ge_Bi):
    print("    {", end="")
    for j, fe_vals in enumerate(point):
        fe51 = portable_to_fe51(fe_vals)
        print(format_fe51(fe51), end="")
        if j < 2:
            print(",")
            print("     ", end="")
    print("}" + ("," if i < 7 else "") )
print("};")

# Generate the ge_base[32][8] table by reading portable values
print()
print()
print("// ge_base[32][8] table in fe51 format (uint64_t[5])")
print("// Converted from portable precomputed base point table")

script_dir = os.path.dirname(os.path.abspath(__file__))
portable_path = os.path.join(script_dir, '..', 'src', 'portable', 'ge_precomp_base.inl')

with open(portable_path, 'r') as f:
    content = f.read()

# Extract all integers from the file (skip comment lines)
# Parse the portable ge_base table: find all fe initializers (groups of 10 integers)
numbers = []
for line in content.split('\n'):
    # Skip comment lines
    stripped = line.strip()
    if stripped.startswith('//') or stripped.startswith('/*') or stripped.startswith('*'):
        continue
    # Extract all integers (including negative)
    nums = re.findall(r'-?\d+', line)
    numbers.extend(int(n) for n in nums)

# Skip leading array dimensions (32, 8) from "ge_base[32][8]"
if len(numbers) > 7680:
    numbers = numbers[len(numbers) - 7680:]
assert len(numbers) == 7680, f"Expected 7680 integers, got {len(numbers)}"

print("static const ge_precomp ge_base[32][8] = {")
idx = 0
for row in range(32):
    print("    {")
    for col in range(8):
        # Each precomp has 3 fe values (yplusx, yminusx, xy2d)
        fes = []
        for k in range(3):
            limbs10 = numbers[idx:idx+10]
            idx += 10
            fe51 = portable_to_fe51(limbs10)
            fes.append(format_fe51(fe51))
        comma = "," if col < 7 else ""
        print(f"     {{{fes[0]},")
        print(f"      {fes[1]},")
        print(f"      {fes[2]}}}{comma}")
    comma = "," if row < 31 else ""
    print(f"    }}{comma}")
print("};")
