#!/usr/bin/env python3
"""
Independent validator for Ed25519 test vectors.

Uses PyNaCl (libsodium bindings) as the reference implementation for all
group element operations, and Python's native modular arithmetic for
scalar and field element operations.

This provides genuine independent validation: the test vectors were
generated by the portable C++ backend, and this script verifies them
against libsodium — a completely separate, well-audited implementation.

Requirements:
    pip install pynacl

Usage:
    python tools/validate_test_vectors.py --validate test_vectors/ed25519_test_vectors.json
"""

import json
import sys
import argparse

try:
    from nacl.bindings import (
        crypto_scalarmult_ed25519_base_noclamp,
        crypto_scalarmult_ed25519_noclamp,
        crypto_core_ed25519_add,
        crypto_core_ed25519_sub,
        crypto_core_ed25519_is_valid_point,
    )
    HAS_NACL = True
except ImportError:
    HAS_NACL = False
    print("WARNING: PyNaCl not installed. Install with: pip install pynacl")
    print("         Group element validation will be skipped.")
    print()

# ============================================================
# Ed25519 constants
# ============================================================

p = 2**255 - 19
l = 2**252 + 27742317777372353535851937790883648493
d = (-121665 * pow(121666, p - 2, p)) % p

# Identity point (compressed): y=1, x=0 (even), sign bit = 0
IDENTITY_BYTES = b'\x01' + b'\x00' * 31

# ============================================================
# Conversion helpers
# ============================================================

def hex_to_bytes(h):
    return bytes.fromhex(h)

def bytes_to_hex(b):
    return b.hex()

def hex_to_int_le(h):
    return int.from_bytes(bytes.fromhex(h), 'little')

def int_to_hex_le(val, length=32):
    val = val % (2 ** (length * 8))
    return val.to_bytes(length, 'little').hex()

def scalar_from_hex(h):
    return hex_to_int_le(h) % l

def fe_from_hex(h):
    raw = hex_to_int_le(h)
    raw &= (2**255 - 1)  # fe_frombytes clears top bit
    return raw % p

# ============================================================
# libsodium-based point operations (with edge case handling)
# ============================================================

def nacl_scalarmult_base(scalar_hex):
    """Compute scalar * B using libsodium. Returns compressed point hex."""
    s = hex_to_bytes(scalar_hex)
    # libsodium rejects zero scalar (returns error for neutral element)
    if s == b'\x00' * 32:
        return bytes_to_hex(IDENTITY_BYTES)
    try:
        result = crypto_scalarmult_ed25519_base_noclamp(s)
        return bytes_to_hex(result)
    except Exception as e:
        return None

def nacl_scalarmult(scalar_hex, point_hex):
    """Compute scalar * P using libsodium. Returns compressed point hex."""
    s = hex_to_bytes(scalar_hex)
    pt = hex_to_bytes(point_hex)
    if s == b'\x00' * 32:
        return bytes_to_hex(IDENTITY_BYTES)
    try:
        result = crypto_scalarmult_ed25519_noclamp(s, pt)
        return bytes_to_hex(result)
    except Exception as e:
        return None

def nacl_point_add(p_hex, q_hex):
    """Compute P + Q using libsodium."""
    P = hex_to_bytes(p_hex)
    Q = hex_to_bytes(q_hex)
    try:
        result = crypto_core_ed25519_add(P, Q)
        return bytes_to_hex(result)
    except Exception as e:
        return None

def nacl_point_sub(p_hex, q_hex):
    """Compute P - Q using libsodium."""
    P = hex_to_bytes(p_hex)
    Q = hex_to_bytes(q_hex)
    try:
        result = crypto_core_ed25519_sub(P, Q)
        return bytes_to_hex(result)
    except Exception as e:
        return None

# ============================================================
# Scalar validation (pure Python modular arithmetic)
# ============================================================

def validate_scalars(data, errors):
    sc = data.get("scalars", {})

    for vec in sc.get("add", []):
        a, b = scalar_from_hex(vec["a"]), scalar_from_hex(vec["b"])
        expected = vec["result"]
        computed = int_to_hex_le((a + b) % l)
        if computed != expected:
            errors.append(f"sc_add '{vec['label']}': expected {expected}, got {computed}")

    for vec in sc.get("sub", []):
        a, b = scalar_from_hex(vec["a"]), scalar_from_hex(vec["b"])
        expected = vec["result"]
        computed = int_to_hex_le((a - b) % l)
        if computed != expected:
            errors.append(f"sc_sub '{vec['label']}': expected {expected}, got {computed}")

    for vec in sc.get("mul", []):
        a, b = scalar_from_hex(vec["a"]), scalar_from_hex(vec["b"])
        expected = vec["result"]
        computed = int_to_hex_le((a * b) % l)
        if computed != expected:
            errors.append(f"sc_mul '{vec['label']}': expected {expected}, got {computed}")

    for vec in sc.get("muladd", []):
        a = scalar_from_hex(vec["a"])
        b = scalar_from_hex(vec["b"])
        c = scalar_from_hex(vec["c"])
        expected = vec["result"]
        computed = int_to_hex_le((a * b + c) % l)
        if computed != expected:
            errors.append(f"sc_muladd '{vec['label']}': expected {expected}, got {computed}")

    for vec in sc.get("mulsub", []):
        a = scalar_from_hex(vec["a"])
        b = scalar_from_hex(vec["b"])
        c = scalar_from_hex(vec["c"])
        expected = vec["result"]
        computed = int_to_hex_le((c - a * b) % l)
        if computed != expected:
            errors.append(f"sc_mulsub '{vec['label']}': expected {expected}, got {computed}")

    for vec in sc.get("reduce32", []):
        raw = hex_to_int_le(vec["input"])
        raw &= (2**255 - 1)
        expected = vec["result"]
        computed = int_to_hex_le(raw % l)
        if computed != expected:
            errors.append(f"sc_reduce32 '{vec['label']}': expected {expected}, got {computed}")

    for vec in sc.get("reduce64", []):
        raw = hex_to_int_le(vec["input"])
        expected = vec["result"]
        computed = int_to_hex_le(raw % l)
        if computed != expected:
            errors.append(f"sc_reduce64 '{vec['label']}': expected {expected}, got {computed}")

    for vec in sc.get("clamp", []):
        raw = bytearray(bytes.fromhex(vec["input"]))
        raw[0] &= 248
        raw[31] &= 127
        raw[31] |= 64
        expected = vec["result"]
        computed = raw.hex()
        if computed != expected:
            errors.append(f"sc_clamp '{vec['label']}': expected {expected}, got {computed}")

    for vec in sc.get("negate", []):
        a = scalar_from_hex(vec["input"])
        expected = vec["result"]
        computed = int_to_hex_le((-a) % l)
        if computed != expected:
            errors.append(f"sc_negate '{vec['label']}': expected {expected}, got {computed}")

# ============================================================
# Field element validation (pure Python modular arithmetic)
# ============================================================

def validate_field_elements(data, errors):
    fe = data.get("field_elements", {})

    for vec in fe.get("roundtrip", []):
        raw = hex_to_int_le(vec["input"])
        raw &= (2**255 - 1)
        canonical = raw % p
        expected = vec["result"]
        computed = int_to_hex_le(canonical)
        if computed != expected:
            errors.append(f"fe_roundtrip '{vec['label']}': expected {expected}, got {computed}")

    def check_fe(name, op_fn):
        if name not in fe:
            return
        vec = fe[name]
        a = fe_from_hex(vec["a"])
        if "b" in vec:
            b = fe_from_hex(vec["b"])
            result = op_fn(a, b)
        else:
            result = op_fn(a)
        expected = vec["result"]
        computed = int_to_hex_le(result % p)
        if computed != expected:
            errors.append(f"fe_{name}: expected {expected}, got {computed}")

    check_fe("add", lambda a, b: (a + b) % p)
    check_fe("sub", lambda a, b: (a - b) % p)
    check_fe("mul", lambda a, b: (a * b) % p)
    check_fe("sq", lambda a: (a * a) % p)
    check_fe("sq2", lambda a: (2 * a * a) % p)
    check_fe("neg", lambda a: (-a) % p)
    check_fe("invert", lambda a: pow(a, p - 2, p))

    # pow22523: a^((p-5)/8)
    if "pow22523" in fe:
        vec = fe["pow22523"]
        a = fe_from_hex(vec["a"])
        exp = (p - 5) // 8
        expected = vec["result"]
        computed = int_to_hex_le(pow(a, exp, p))
        if computed != expected:
            errors.append(f"fe_pow22523: expected {expected}, got {computed}")

# ============================================================
# Group element validation (via libsodium / PyNaCl)
# ============================================================

def validate_group_elements(data, errors):
    if not HAS_NACL:
        errors.append("SKIPPED: group element validation requires PyNaCl (pip install pynacl)")
        return

    ge = data.get("group_elements", {})

    # Generator: 1*B
    if "generator" in ge:
        expected = ge["generator"]
        computed = nacl_scalarmult_base("01" + "00" * 31)
        if computed != expected:
            errors.append(f"generator: expected {expected}, got {computed}")

    # Identity: 0*B
    if "identity" in ge:
        expected = ge["identity"]
        computed = bytes_to_hex(IDENTITY_BYTES)
        if computed != expected:
            errors.append(f"identity: expected {expected}, got {computed}")

    # scalar_mul_base: s * B
    for vec in ge.get("scalar_mul_base", []):
        expected = vec["result"]
        computed = nacl_scalarmult_base(vec["scalar"])
        if computed is None:
            errors.append(f"scalar_mul_base '{vec['label']}': libsodium error")
        elif computed != expected:
            errors.append(f"scalar_mul_base '{vec['label']}': expected {expected}, got {computed}")

    # scalar_mul_varbase: s * P
    for vec in ge.get("scalar_mul_varbase", []):
        expected = vec["result"]
        computed = nacl_scalarmult(vec["scalar"], vec["point"])
        if computed is None:
            errors.append(f"scalar_mul_varbase '{vec['label']}': libsodium error")
        elif computed != expected:
            errors.append(f"scalar_mul_varbase '{vec['label']}': expected {expected}, got {computed}")

    # double_scalar_mul_base: ge_double_scalarmult_base_negate_vartime(r, a, A, b)
    # Despite the "negate" in the name, the implementation computes r = a*A + b*B
    # (see portable source line 71: "r = a * A + b * B")
    for vec in ge.get("double_scalar_mul_base", []):
        expected = vec["result"]
        a_hex, A_hex, b_hex = vec["a"], vec["A"], vec["b"]

        aA = nacl_scalarmult(a_hex, A_hex)
        bB = nacl_scalarmult_base(b_hex)

        # Compute a*A + b*B = add(aA, bB)
        if aA is None and bB is None:
            computed = bytes_to_hex(IDENTITY_BYTES)
        elif aA is None:
            computed = bB
        elif bB is None:
            computed = aA
        else:
            computed = nacl_point_add(aA, bB)

        if computed is None:
            errors.append(f"dsm_base '{vec['label']}': libsodium error in point_sub")
        elif computed != expected:
            errors.append(f"dsm_base '{vec['label']}': expected {expected}, got {computed}")

    # MSM: sum(s_i * P_i)
    for vec in ge.get("msm", []):
        n = vec["n"]
        scalars_hex = vec["scalars"]
        points_hex = vec["points"]
        expected = vec["result"]

        accum = None  # None means identity
        all_ok = True
        for i in range(n):
            term = nacl_scalarmult(scalars_hex[i], points_hex[i])
            # term is None means zero scalar → identity (contributes nothing)
            if term is None:
                continue
            if accum is None:
                accum = term
            else:
                accum = nacl_point_add(accum, term)
                if accum is None:
                    errors.append(f"msm n={n}: libsodium error at index {i}")
                    all_ok = False
                    break

        if all_ok:
            if accum is None:
                computed = bytes_to_hex(IDENTITY_BYTES)
            else:
                computed = accum
            if computed != expected:
                errors.append(f"msm n={n}: expected {expected}, got {computed}")

    # frombytes valid/invalid
    fb = ge.get("frombytes", {})
    for vec in fb.get("valid", []):
        pt_bytes = hex_to_bytes(vec["input"])
        rc = vec["rc"]
        is_valid = crypto_core_ed25519_is_valid_point(pt_bytes)
        if rc == 0 and not is_valid:
            # Special case: identity (01 00...00) may not be "valid" per libsodium
            # (libsodium considers the neutral element invalid for some functions)
            if pt_bytes != IDENTITY_BYTES:
                errors.append(f"frombytes valid '{vec['label']}': libsodium says invalid")
        if rc != 0 and is_valid:
            errors.append(f"frombytes valid '{vec['label']}': libsodium says valid but library rejected")

    for vec in fb.get("invalid", []):
        rc = vec["rc"]
        if rc == 0:
            errors.append(f"frombytes invalid '{vec['label']}': library accepted invalid point")

    # Wei25519: X_wei = u + A/3 where u = (1+y)/(1-y), A=486662
    # Decode the point, get y, compute u, compute X_wei
    A_mont = 486662
    A_over_3 = (A_mont * pow(3, p - 2, p)) % p
    for vec in ge.get("wei25519", []):
        # Compute the point via libsodium
        pt_hex = nacl_scalarmult_base(vec["scalar"])
        if pt_hex is None:
            errors.append(f"wei25519: libsodium scalarmult failed")
            continue
        # Decode y from compressed point
        pt_bytes = hex_to_bytes(pt_hex)
        y = int.from_bytes(pt_bytes, 'little') & ((1 << 255) - 1)
        # u = (1+y)/(1-y) mod p
        u = ((1 + y) * pow((1 - y) % p, p - 2, p)) % p
        x_wei = (u + A_over_3) % p
        expected = vec["wei25519_x"]
        computed = int_to_hex_le(x_wei)
        if computed != expected:
            errors.append(f"wei25519 scalar={vec['scalar'][:8]}...: expected {expected}, got {computed}")

# ============================================================
# Ristretto255 validation (structure checks)
# ============================================================

def validate_ristretto(data, errors):
    rist = data.get("ristretto255", {})

    for vec in rist.get("roundtrip", []):
        if vec["decode_rc"] != 0:
            errors.append(f"ristretto roundtrip '{vec['label']}': decode failed")
        if vec["encoded"] != vec["re_encoded"]:
            errors.append(f"ristretto roundtrip '{vec['label']}': re-encode mismatch")

    for vec in rist.get("roundtrip", []):
        if vec["label"] == "0*G":
            if vec["encoded"] != "00" * 32:
                errors.append(f"ristretto identity should be all zeros, got {vec['encoded']}")

# ============================================================
# Main
# ============================================================

def main():
    parser = argparse.ArgumentParser(description="Validate Ed25519 test vectors")
    parser.add_argument("--validate", required=True, help="Path to JSON test vectors file")
    args = parser.parse_args()

    with open(args.validate, 'r') as f:
        data = json.load(f)

    errors = []

    print(f"Validating test vectors (version {data.get('version', '?')})...")
    print(f"Generator: {data.get('generator', '?')}")
    if HAS_NACL:
        print(f"Reference: PyNaCl (libsodium)")
    print()

    print("Validating scalars...")
    n_before = len(errors)
    validate_scalars(data, errors)
    print(f"  {'PASS' if len(errors) == n_before else 'FAIL'}")

    print("Validating field elements...")
    n_before = len(errors)
    validate_field_elements(data, errors)
    print(f"  {'PASS' if len(errors) == n_before else 'FAIL'}")

    print("Validating group elements...")
    n_before = len(errors)
    validate_group_elements(data, errors)
    print(f"  {'PASS' if len(errors) == n_before else 'FAIL'}")

    print("Validating ristretto255...")
    n_before = len(errors)
    validate_ristretto(data, errors)
    print(f"  {'PASS' if len(errors) == n_before else 'FAIL'}")

    print()
    if errors:
        print(f"FAILED: {len(errors)} error(s)")
        for e in errors:
            print(f"  ERROR: {e}")
        sys.exit(1)
    else:
        print("ALL VECTORS VALIDATED SUCCESSFULLY")
        sys.exit(0)

if __name__ == "__main__":
    main()
